### ISSUE TITLE
Implement Namespace Finalization

### ISSUE THREAD

**Issue by nexus49** [openmfp/account-operator#37]
### Context
Currently the account-operator does not yet implement namespace finalization.

When an account is created, the operator creates a new managed namespace for this account as part of the Namespace Subroutine [link](https://github.com/openmfp/account-operator/blob/main/pkg/subroutines/namespace.go)

### Tasks

- Implement and test the namespace deletion as part of the namespace subroutine.
- The subroutine should only remove the Finalizer after the namespace was removed successfully (waiting for it to be deleted)

**Comment by aaronschweig** [comment]
Done in #40
